package com.goodNews.genesis.shared.enums;

public enum SedesEnum {
	VENTANILLA, VILLA_SALVADOR, HUAYCAN, LIMA_CENTRO,MANCHAY, 
	AMAZONAS, ANCASH, APURIMAC, AREQUIPA, AYACUCHO, CAJAMARCA, 
	CALLAO, CUSCO, HUANCAVELICA, HUANUCO, ICA, JUNIN, LA_LIBERTAD, 
	LAMBAYEQUE,LORETO, MADRE_DE_DIOS, MOQUEGUA, PASCO, PIURA,
	PUNO, SAN_MARTIN, TACNA, TUMBES, UCAYALI

}


